In [232]:
import pandas as pd
import numpy as np

In [234]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score,roc_auc_score, f1_score
from sklearn.linear_model import LogisticRegression

In [236]:
dataset = pd.read_excel(r"C:\Users\Shreya\Downloads\Credit_scoring_project\a_Dataset_CreditScoring.xlsx")

In [237]:
## Exploeing the dataset
dataset.shape

(3000, 30)

In [238]:
dataset.head()

TARGET    ID  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
0       1   582         3           3             0         4          0.0   
1       1   662        15           9             0         3          1.0   
2       1   805         0           0             0         1          5.0   
3       1  1175         8           5             0         6          1.0   
4       1  1373         3           1             0         9          0.0   

   InqFinanceCnt24  TLTimeFirst  TLTimeLast  ...  TL50UtilCnt  TLBalHCPct  \
0                5          117          27  ...          3.0      0.9179   
1                3           14          14  ...          1.0      0.8000   
2                1          354           7  ...          5.0      0.3552   
3               10           16           4  ...          3.0      0.9127   
4                8          130          52  ...          1.0      1.2511   

   TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  TLDel60CntAll  TLOpenPct  \
0    0.2083               2             3              7     0.2083   
1    0.0000               0             0              0     1.0000   
2    0.6538               0             1              1     0.7308   
3    0.2500               1             1              1     0.7500   
4    0.0000               0             1              4     0.1429   

   TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
0              4             4       0.0000  
1             12             0       1.0000  
2              1             1       0.5263  
3              7             1       1.3333  
4              3             1       0.0000  

[5 rows x 30 columns]

In [239]:
dataset = dataset.drop('ID',axis=1)

In [240]:
dataset.isna().sum()

TARGET               0
DerogCnt             0
CollectCnt           0
BanruptcyInd         0
InqCnt06             0
InqTimeLast        188
InqFinanceCnt24      0
TLTimeFirst          0
TLTimeLast           0
TLCnt03              0
TLCnt12              0
TLCnt24              0
TLCnt                3
TLSum               40
TLMaxSum            40
TLSatCnt             4
TLDel60Cnt           0
TLBadCnt24           0
TL75UtilCnt         99
TL50UtilCnt         99
TLBalHCPct          41
TLSatPct             4
TLDel3060Cnt24       0
TLDel90Cnt24         0
TLDel60CntAll        0
TLOpenPct            3
TLBadDerogCnt        0
TLDel60Cnt24         0
TLOpen24Pct          3
dtype: int64

In [241]:
dataset = dataset.fillna(dataset.mean())

In [242]:
dataset.isna().sum()

TARGET             0
DerogCnt           0
CollectCnt         0
BanruptcyInd       0
InqCnt06           0
InqTimeLast        0
InqFinanceCnt24    0
TLTimeFirst        0
TLTimeLast         0
TLCnt03            0
TLCnt12            0
TLCnt24            0
TLCnt              0
TLSum              0
TLMaxSum           0
TLSatCnt           0
TLDel60Cnt         0
TLBadCnt24         0
TL75UtilCnt        0
TL50UtilCnt        0
TLBalHCPct         0
TLSatPct           0
TLDel3060Cnt24     0
TLDel90Cnt24       0
TLDel60CntAll      0
TLOpenPct          0
TLBadDerogCnt      0
TLDel60Cnt24       0
TLOpen24Pct        0
dtype: int64

In [243]:
dataset.shape
dataset.head()

TARGET  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
0       1         3           3             0         4          0.0   
1       1        15           9             0         3          1.0   
2       1         0           0             0         1          5.0   
3       1         8           5             0         6          1.0   
4       1         3           1             0         9          0.0   

   InqFinanceCnt24  TLTimeFirst  TLTimeLast  TLCnt03  ...  TL50UtilCnt  \
0                5          117          27        0  ...          3.0   
1                3           14          14        0  ...          1.0   
2                1          354           7        0  ...          5.0   
3               10           16           4        0  ...          3.0   
4                8          130          52        0  ...          1.0   

   TLBalHCPct  TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  TLDel60CntAll  \
0      0.9179    0.2083               2             3              7   
1      0.8000    0.0000               0             0              0   
2      0.3552    0.6538               0             1              1   
3      0.9127    0.2500               1             1              1   
4      1.2511    0.0000               0             1              4   

   TLOpenPct  TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
0     0.2083              4             4       0.0000  
1     1.0000             12             0       1.0000  
2     0.7308              1             1       0.5263  
3     0.7500              7             1       1.3333  
4     0.1429              3             1       0.0000  

[5 rows x 29 columns]

In [244]:
dataset['TARGET'].value_counts()  ## count of good loans (0) and bad loans (1)

TARGET
0    2500
1     500
Name: count, dtype: int64

In [245]:
# # data summary across 0 & 1
#dataset.groupby('TARGET')['DerogCnt'].mean()   
dataset.groupby('TARGET').mean()

DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
TARGET                                                              
0         1.3224      0.7664        0.1492    2.9424     3.174638   
1         1.9680      1.3100        0.1740    3.9380     2.775459   

        InqFinanceCnt24  TLTimeFirst  TLTimeLast  TLCnt03  TLCnt12  ...  \
TARGET                                                              ...   
0                3.2896      173.002      11.650   0.2844    1.832  ...   
1                4.8820      155.672      12.992   0.2280    1.768  ...   

        TL50UtilCnt  TLBalHCPct  TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  \
TARGET                                                                    
0          3.986711    0.628177  0.544963          0.6044        0.6624   
1          4.533870    0.748185  0.385173          1.3340        1.5760   

        TLDel60CntAll  TLOpenPct  TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
TARGET                                                                      
0              2.2236   0.502376          1.180        0.8648     0.556867  
1              4.0140   0.465127          2.554        2.0860     0.600978  

[2 rows x 28 columns]

Train Test Split

In [254]:
# df[start_row:end_row:step, start_col:end_col:step]

y = dataset.iloc[:,0]
x = dataset.iloc[:, 1:]


In [258]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state = 0)        #The random_state=0 ensures that the same data points are used for testing every time the code is run.

In [261]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

Risk Model Building

In [264]:
classifier = LogisticRegression()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

In [266]:
print(confusion_matrix(y_test,y_pred))

[[482  16]
 [ 88  14]]


In [268]:
print(accuracy_score(y_test,y_pred))

0.8266666666666667


In [270]:
print(f1_score(y_test,y_pred))

0.21212121212121213


In [272]:
print(recall_score(y_test,y_pred))

0.13725490196078433


In [274]:
print(precision_score(y_test,y_pred))

0.4666666666666667


In [276]:
print(roc_auc_score(y_test,y_pred))

0.5525631939522797


In [278]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=0)
x1, y1 = smote.fit_resample(x_train, y_train)  # New resampled training set


In [280]:
sc = StandardScaler()
x1 = sc.fit_transform(x1)  # Fit on resampled training data
x_test = sc.transform(x_test)  # Transform test data (NO fitting to prevent data leakage)


In [282]:
model = LogisticRegression()
model.fit(x1, y1)  # Train on resampled dataset
y_pred = model.predict(x_test)  # Predict on test set
y_pred = model.predict(x_test)  # Predict on test set

In [284]:
# Confusion Matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[377 121]
 [ 34  68]]


In [286]:
print(f1_score(y_test,y_pred))

0.46735395189003437


In [288]:
print(recall_score(y_test,y_pred))

0.6666666666666666


In [290]:
print(roc_auc_score(y_test,y_pred))

0.7118473895582329


In [292]:
predictions = classifier.predict_proba(x_test)
predictions

array([[0.07140028, 0.92859972],
       [0.96018058, 0.03981942],
       [0.78670793, 0.21329207],
       ...,
       [0.97986774, 0.02013226],
       [0.57667678, 0.42332322],
       [0.90654075, 0.09345925]])

In [299]:
# Check the first few rows of y_test to confirm it's in the correct format
print(y_test.head())

# Ensure that y_test is a pandas Series, and reset its index (if necessary) to avoid misalignment
df_test_dataset = pd.DataFrame(y_test).reset_index(drop=True)

# Check the index of the DataFrames to ensure they match
print(df_test_dataset.index)
print(df_prediction_prob.index)
print(df_prediction_target.index)

# Concatenate actual outcomes, predicted probabilities, and predicted class labels into one DataFrame
dfx = pd.concat([df_test_dataset, df_prediction_prob, df_prediction_target], axis=1)

# Save the DataFrame to a CSV file
dfx.to_csv(r"C:\Users\Shreya\Downloads\Credit_scoring_project\results.csv", sep=',', encoding='UTF-8', index=False)

# Display the first few rows of the result DataFrame to verify everything is correct
dfx.head()


311     1
1025    0
1587    0
2941    0
2980    0
Name: TARGET, dtype: int64
RangeIndex(start=0, stop=600, step=1)
RangeIndex(start=0, stop=600, step=1)
RangeIndex(start=0, stop=600, step=1)


TARGET    prob_0    prob_1  predicted_TARGET
0       1  0.071400  0.928600                 1
1       0  0.960181  0.039819                 0
2       0  0.786708  0.213292                 0
3       0  0.939565  0.060435                 0
4       0  0.909347  0.090653                 0